### ISSUE TITLE
Closed vs Open site

### ISSUE THREAD

**Issue by joshp23** [madbob/GNUS#1]
It seems as if this will work with a public site. It there a way for this to work with a site that is invite only?

**Comment by madbob** [comment]
Actually there is not any kind of authentication. Do you mean permit registration of local accounts, and ability to add new feeds only to authenticated users?

**Comment by joshp23** [comment]
Doesn't GNUS need to be able to create a new account for each feed that it serves? If the gnusocial installation is set to 'closed' or 'invite only' will GNUS still work?

**Comment by madbob** [comment]
No, it uses the (mostly undocumented) API to programmatically register new accounts
https://git.gnu.io/gnu/gnu-social/blob/master/actions/apiaccountregister.php
The API accepts also an invitation code, when required, but GNUS do not (actually) handles this information.

**Comment by joshp23** [comment]
Just to make this clear, if your GNU Social site is set to either   

`$config['site']['closed'] = 'true';`
or   
`$config['site']['inviteonly'] = 'true';`


Then this script will NOT work.
